[package]
name = "gpgme"
version = "0.9.2"
edition = "2018"
authors = ["John Schug <john.ips.schug@gmail.com>"]
license = "LGPL-2.1"
readme = "README.md"
repository = "https://github.com/gpg-rs/gpgme"
documentation = "https://docs.rs/gpgme"
categories = ["api-bindings"]
keywords = ["gpg", "gpgme", "crypto", "cryptography"]
description = "GPGme bindings for Rust"
autotests = false

[badges]
travis-ci = { repository = "gpg-rs/gpgme" }
maintenance = { status = "experimental" }

[features]
nightly = []

[dev-dependencies]
structopt = "0.3"
tempdir = "0.3"

[dependencies]
bitflags = "1"
conv = "0.3"
cstr-argument = "0.1"
gpg-error = "0.5.1"
libc = "0.2"
once_cell = "1"
smallvec = "1"
static_assertions = "1.1"

[dependencies.ffi]
package = "gpgme-sys"
path = "gpgme-sys"
version = "0.9.1"

[[bin]]
name = "pinentry"
test = false

[[test]]
name = "keylist"

[[test]]
name = "encrypt_simple"

[[test]]
name = "encrypt_symmetric"

[[test]]
name = "verify"

[[test]]
name = "edit"

[[test]]
name = "context"

[[test]]
name = "keysign"

[workspace]
members = ["systest"]
